### PR TITLE
Add client sdk for number of docs api

### PR DESCRIPTION
**Pull request by RMPall**
### What

Add client sdk for number of docs api.

### How to review

Please check if the changes make sense.

### Who can review

Anyone except me.

### CODE REVIEW

**Review by justinpjose — COMMENTED** [review]
This looks good. Unit test needs to be written for the client function

**Comment by RMPall** [comment]
> This looks good. Unit test needs to be written for the client function
I think none of the client sdk has been unit tested, there is only one test for the etag header. This makes sense as all the sdks are just calling the api endpoints, so there is not much value that you can get from this.

**Comment by RMPall** [comment]
> This looks good. Unit test needs to be written for the client function

Not sure if it adds any value here as the endpoints are clearly unit tested . This is just an sdk reaching out to the endpoint. Anyways the tests are added.

**Comment by justinpjose** [comment]
> > This looks good. Unit test needs to be written for the client function
> 
> Not sure if it adds any value here as the endpoints are clearly unit tested . This is just an sdk reaching out to the endpoint. Anyways the tests are added.

it’s worth having good test coverage even on ones that don’t add much value

**Pull request merged**
